import { Model, DataTypes } from 'sequelize';
import db from '../config/database2.js';

class Client extends Model {
  static init(sequelize) {
    super.init({
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        nome: DataTypes.STRING,
        email: DataTypes.STRING,
        endereco: DataTypes.STRING,
        bairro: DataTypes.STRING,
        cidade: DataTypes.STRING,
        cep: DataTypes.STRING,
        estado: DataTypes.STRING,
        cpf_cnpj: DataTypes.STRING,
        fone: DataTypes.STRING,
        obs: DataTypes.TEXT,
        nascimento: DataTypes.STRING,
        estado_civil: DataTypes.ENUM('S', 'C', 'D', 'V'),
        cadastro: DataTypes.DATE,
        login: DataTypes.STRING,
        tipo: DataTypes.STRING,
        night: DataTypes.STRING,
        aviso: DataTypes.TEXT,
        foto: DataTypes.STRING,
        venc: DataTypes.STRING,
        mac: DataTypes.STRING,
        complemento: DataTypes.STRING,
        ip: DataTypes.STRING,
        ramal: DataTypes.STRING,
        rg: DataTypes.STRING,
        isento: DataTypes.BOOLEAN,
        celular: DataTypes.STRING,
        bloqueado: DataTypes.ENUM('sim', 'nao'),
        autoip: DataTypes.ENUM('sim', 'nao'),
        automac: DataTypes.ENUM('sim', 'nao'),
        conta: DataTypes.STRING,
        ipvsix: DataTypes.STRING,
        plano: DataTypes.STRING,
        send: DataTypes.STRING,
        cli_ativado: DataTypes.ENUM('s', 'n'),
        simultaneo: DataTypes.STRING,
        turbo: DataTypes.STRING,
        comodato: DataTypes.STRING,
        observacao: DataTypes.ENUM('sim', 'nao'),
        chavetipo: DataTypes.STRING,
        chave: DataTypes.STRING,
        contrato: DataTypes.STRING,
        ssid: DataTypes.STRING,
        senha: DataTypes.STRING,
        numero: DataTypes.STRING,
        responsavel: DataTypes.STRING,
        nome_pai: DataTypes.STRING,
        nome_mae: DataTypes.STRING,
        expedicao_rg: DataTypes.STRING,
        naturalidade: DataTypes.STRING,
        acessacen: DataTypes.STRING,
        pessoa: DataTypes.STRING,
        endereco_res: DataTypes.STRING,
        numero_res: DataTypes.STRING,
        bairro_res: DataTypes.STRING,
        cidade_res: DataTypes.STRING,
        cep_res: DataTypes.STRING,
        estado_res: DataTypes.STRING,
        complemento_res: DataTypes.STRING,
        desconto: DataTypes.DECIMAL,
        acrescimo: DataTypes.DECIMAL,
        equipamento: DataTypes.STRING,
        vendedor: DataTypes.STRING,
        nextel: DataTypes.STRING,
        accesslist: DataTypes.ENUM('sim', 'nao'),
        resumo: DataTypes.STRING,
        grupo: DataTypes.STRING,
        codigo: DataTypes.STRING,
        prilanc: DataTypes.ENUM('pro', 'tot'),
        tipobloq: DataTypes.ENUM('aut', 'man'),
        adesao: DataTypes.DECIMAL,
        mbdisco: DataTypes.INTEGER,
        sms: DataTypes.ENUM('sim', 'nao'),
        ltrafego: DataTypes.BIGINT,
        planodown: DataTypes.STRING,
        ligoudown: DataTypes.STRING,
        statusdown: DataTypes.ENUM('on', 'off'),
        statusturbo: DataTypes.ENUM('on', 'off'),
        opcelular: DataTypes.STRING,
        nome_res: DataTypes.STRING,
        coordenadas: DataTypes.STRING,
        rem_obs: DataTypes.DATE,
        valor_sva: DataTypes.DECIMAL,
        dias_corte: DataTypes.INTEGER,
        user_ip: DataTypes.STRING,
        user_mac: DataTypes.STRING,
        data_ip: DataTypes.DATE,
        data_mac: DataTypes.DATE,
        last_update: DataTypes.DATE,
        data_bloq: DataTypes.DATE,
        tags: DataTypes.TEXT,
        tecnico: DataTypes.STRING,
        data_ins: DataTypes.DATE,
        altsenha: DataTypes.ENUM('sim', 'nao'),
        geranfe: DataTypes.ENUM('sim', 'nao'),
        mesref: DataTypes.ENUM('now', 'ant'),
        ipfall: DataTypes.STRING,
        tit_abertos: DataTypes.INTEGER,
        parc_abertas: DataTypes.INTEGER,
        tipo_pessoa: DataTypes.INTEGER,
        celular2: DataTypes.STRING,
        mac_serial: DataTypes.STRING,
        status_corte: DataTypes.ENUM('full','down','bloq'),
        plano15: DataTypes.STRING,
        pgaviso: DataTypes.ENUM('sim', 'nao'),
        porta_olt: DataTypes.STRING,
        caixa_herm: DataTypes.STRING,
        porta_splitter: DataTypes.STRING,
        onu_ont: DataTypes.STRING,
        switch: DataTypes.STRING,
        tit_vencidos: DataTypes.INTEGER,
        pgcorte: DataTypes.ENUM('sim', 'nao'),
        interface: DataTypes.STRING,
        login_atend: DataTypes.STRING,
        cidade_ibge: DataTypes.STRING,
        estado_ibge: DataTypes.STRING,
        data_desbloq: DataTypes.DATE,
        pool_name: DataTypes.STRING,
        pool6: DataTypes.STRING,
        rec_email: DataTypes.ENUM('sim', 'nao'),
        dot_ref: DataTypes.STRING,
        conta_cartao: DataTypes.INTEGER,
        termo: DataTypes.STRING,
        opcelular2: DataTypes.STRING,
        tipo_cliente: DataTypes.INTEGER,
        armario_olt: DataTypes.STRING,
        plano_bloqc: DataTypes.STRING,
        uuid_cliente: DataTypes.STRING,
        data_desativacao: DataTypes.DATE,
        tipo_cob: DataTypes.ENUM('titulo','carne'),
        fortunus: DataTypes.TINYINT,
        gsici: DataTypes.TINYINT,
        local_dici: DataTypes.ENUM('u','r')
    }, {
      sequelize,
      modelName: 'Client',
      tableName: 'sis_cliente', // Substitua pelo nome da sua tabela
      timestamps: false,
    });

    return this;
  }
}

Client.init(db);

export default Client;
